services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db/lu_estilo
    depends_on:
      - db
    volumes:
      - ./app:/app/app
      - ./migrations:/app/migrations

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lu_estilo
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
